### ISSUE TITLE
Issues opening the dxf file

### ISSUE THREAD

**Issue by baovuong** [googlecreativelab/open-nsynth-super#10]
I cloned the repo and opened the dxf file in DWG TrueView. 

I get the following error when doing so:

![image](https://user-images.githubusercontent.com/3112262/37474106-f602f136-2845-11e8-9b57-e211d2aea6b6.png)

**Comment by sqfmi** [comment]
@baovuong try opening it with Autodesk viewer https://viewer.autodesk.com/ seems to work for me: http://autode.sk/2FG3JQX

**Comment by nsynthsuper** [comment]
The file can be opened in Inkscape, Illustrator and other vector graphics tools; you may need to re-export from one of those packages or convert the format if the file isn't opening in TrueView.
