### ISSUE TITLE
Can't setup network

### ISSUE THREAD

**Issue by doodlegabe** [googlecreativelab/open-nsynth-super#11]
When trying to use `sudo wpa_cli` it hangs 'Could not connect to wpa_suplicant:wlan0 - re-trying`. When I trace the wpa_cli I see it repeating that it's a read-only file system.  

Do we need to set up an new wpa_supplicant.conf someplace outside the locked image?

----

Was able to connect by remounting and editing the wpa config. Maybe instruction change?

**Comment by nsynthsuper** [comment]
You can temporarily remount the filesystem as rw to make changes to configuration:

`$ sudo mount -o remount,rw /`

When you reboot the filesystem will mount as RO again, unless you update that setting in fstab (it's recommended to keep as RO to protect against cuts of power)
