### ISSUE TITLE
Raspberry Pi mounting

### ISSUE THREAD

**Issue by FHIM** [googlecreativelab/open-nsynth-super#14]
I've been going through the documentation to see how the Raspberry Pi needs to be mounted, but I couldn't find any pictures. Everything else, like the OLED, the enclosure and all the mechanical parts is very well documented (hats off!), but it seems to be missing for the R Pi.

**Comment by KyleWerle** [comment]
The USB ports go towards the potentiometers. If you try to put it in any other way the rPi will be extruding pretty far off the main board.

I currently have an updated laser cut file for exposing the USB ports on the rPi.

**Comment by FHIM** [comment]
Ah, thanks for your quick response!
