### ISSUE TITLE
Touchscreen

### ISSUE THREAD

**Issue by relaxis** [googlecreativelab/open-nsynth-super#15]
Hi there, I can see a massive difference between this model and the one posted by Google which is the touchscreen is missing from this design. Is there a way to include the touchscreen from adafruit instead of the capacitative pad?

**Comment by panfriedcharlie** [comment]
@relaxis This was addressed in a [previous issue](https://github.com/googlecreativelab/open-nsynth-super/issues/5), since closed. The answer is you will have to design, build, and program such an implementation yourself. 😄Quote:

> the unit you refer to with the touch screen was designed as an experience prototype for developing the interface and we have no plans to release the source files.

**Comment by relaxis** [comment]
Righto, what did I expect from an "open" project from Google.
