### ISSUE TITLE
Multidimensional Polyphonic Expression (MPE) Support?

### ISSUE THREAD

**Issue by EchozAurora** [googlecreativelab/open-nsynth-super#17]
I'm on a waitlist to order a PCB to build an NSynth Super at the moment so it may be a bit before I'm able to test this, but I'm curious whether MPE is supported by this?

If not familiar, this is a new specification recently adopted by MIDI and allows multidimensional controllers such as the LinnStrument and Seaboard to add pitch bends, vibrato, etc to individual notes rather than the all of the notes played simultaneously.

If not currently an option, I'd love to see it in a future addition to the hardware/software 👍 

Here is a link to MIDI's release on the standard for more info:
https://www.midi.org/articles/midi-polyphonic-expression-mpe

**Comment by nsynthsuper** [comment]
The unit currently supports MIDI notes and velocity, but this would be a terrific thing to add to the code.
