### ISSUE TITLE
Maximum Resolution for Capacitive Grid

### ISSUE THREAD

**Issue by KyleWerle** [googlecreativelab/open-nsynth-super#19]
Currently the capacitive touch grid is mapped to 0-10 or a point per touch IC sensor on each axis.

Is it possible to map the cap touch grid to a higher resolution? 
Looking at the datasheet for the ICs suggests it is possible for much higher resolution with triangular trace designs.

**Comment by nsynthsuper** [comment]
Hi Kyle – this would be an interesting experiment for sure. Bear in mind that you'll have to increase the resolution of the audio generation as well to match, which will result in larger audio binaries, fewer combinations, or a much larger SD card.
