### ISSUE TITLE
Compatible with Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by jonas18z** [googlecreativelab/open-nsynth-super#20]
Is this Compatible with Raspberry Pi 3 Model B or only the standard Pi3?

**Comment by KyleWerle** [comment]
The new one is the rPi 3 b+. I am also curious. I currently have 2 NSynth Supers on rPi 3 model b and they run well.

**Comment by nsynthsuper** [comment]
This hasn't yet been tested with the 3B+. It is likely that it will **not** work out of the box, however, as it looks like the 3B+ requires the latest version of Raspbian; some effort & debugging will probably be needed to get everything running with the latest board.
