### ISSUE TITLE
Cloning OpenOCD fails in nsynth-setup.sh

### ISSUE THREAD

**Issue by SarahHopeB** [googlecreativelab/open-nsynth-super#22]
The git tree on sf.net for openocd is down, [reference here](http://sourceforge.net/p/openocd/code/).  The Nsynth bash file would hang on the "Cloning into 'openocd' step.  I had to modify nsynth-setup.sh to pull from the [secondary (official) git repo](http://repo.or.cz/w/openocd.git) for openOCD:

git://repo.or.cz/openocd.git

(This is for future info... not really a bug, but in case someone else runs into the same issue in the meantime)

**Comment by nsynthsuper** [comment]
Thanks for the info Sarah
