### ISSUE TITLE
Potentiometers instead of rotary encoders ?

### ISSUE THREAD

**Issue by minijouin** [googlecreativelab/open-nsynth-super#33]
Hi !

I'm wondering if it could be possible to put some potentiometers instead of the 4 rotary encoders in the corners (the good reference is impossible to find on the internet and I had the one with 2 more arms -or could I cut them ?- )

Thanks !

**Comment by fakemau5** [comment]
If you mean you got the "S0012" variant of the encoders, you're good to go. They have a "push button" feature, so they have the two more arms that are going to be short-circuited when you press the button, but given the "button" feature of the encoders is not used you can safely cut or bend them to fit on the board, and they will perform fine!

**Comment by minijouin** [comment]
Ok thank you so much !
