### ISSUE TITLE
Playback open error

### ISSUE THREAD

**Issue by tekfunk** [googlecreativelab/open-nsynth-super#36]
I am so close to getting this working. Even though my display wont power on, I can use the HDMI port on the pi to check everything out.  Nsynth is running, and all the knobs + touchpad work.  When I run the speaker-test, however, I get an error:

Playback open error: -16, Device or resource busy

Any ideas on what could be causing this?

Thanks

**Comment by Wolfberti** [comment]
May I ask you what kind of speaker-test you run?

**Comment by sqfmi** [comment]
try stopping the open-nsynth service before running speaker-test

**Comment by nsynthsuper** [comment]
As mentioned by @sqfmi – the open-nsynth application will hold the audio card and prevent speaker-test from running.
