### ISSUE TITLE
Gracefully shutdown the nsynth raspberry

### ISSUE THREAD

**Issue by fakemau5** [googlecreativelab/open-nsynth-super#57]
Once the device is up&running as a standalone synth, is there any way or guideline to gracefully invoke the raspberry shutdown from the hardware user interface?

**Comment by nsynthsuper** [comment]
If you're running from the provided images then the OS runs in RO mode to protect the contents of the disk. 

However you if you created a UX for this (for example, if the volume control is set to zero) you could add the functionality to the application itself. By default, it isn't needed.
